# Generated by Django 5.1.6 on 2025-02-27 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_image_url_alter_product_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='imageUrl',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='imageUrl',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
